### ISSUE TITLE
Severe Cow Lag

### ISSUE THREAD

**Issue by JGamerXone** [Propogo89/Stormcraft-support#6]
Cows move super slowly, and apparently won't breed

**Comment by Propogo89** [comment]
Thanks for notifying us we will look into this

**Comment by Propogo89** [comment]
Have you been feeding them

**Comment by Propogo89** [comment]
It might be that 1.14 when releasee was detected with a lot of bugs if you check the official Minecraft bug catcher page you can see what some of them are and should be fixed in 1.14.1 which should come out soon

**Comment by Stormcraft-Net** [comment]
For now fixed by terminating the herd and respawning (maybe they were all bulls? ;) )

**Comment by Propogo89** [comment]
Here's the link to the bug tracker @JGamerXone  [https://www.minecraft.net/en-us/bugs/](url)

**Comment by JGamerXone** [comment]
Btw pictures are still disabled in the memes section
![image](https://user-images.githubusercontent.com/42722082/57562757-3fbbc800-735b-11e9-80ec-185b1e951893.png)
